js/components/bottom-panel.js
js/components/plates.js

Demo: 
http://models-resources.concord.org/plate-tectonics-3d/branch/pause-control/index.html?preset=subduction

Add pause/play controls

---

js/components/authoring.js
js/components/plates.js

Hi @pjanik, I think this takes care of the back button! Seems to pass `lint` as well. Let me know what you think - maybe we can take a look at it together tomorrow after standup.

Adding authoring back button

---

js/plates-model/volcanic-activity.js

Small one. 😉 
I might refactor `.isOcean` property soon. Also, not sure if we need separate `.island` property, but let's see. I'm working on other island-related features anyway.

Make volcanic islands continental crust in cross-section

---

js/config.js
js/plates-model/get-cross-section.js
js/plates-model/plate.js
js/plates-view/render-cross-section.js
js/presets.js

A few tweaks related to Amy's requests (see commit messages).
Cross-section offset issue was pretty difficult to find. I'm not a fan of cross-section code, as it's trying to do too much, but well, it's all based on feature requests. I've added comments, so hopefully, it's clear more or less.

Cross-section and island collision tweaks

---

css/bottom-panel.less
css/sidebar-menu.less
js/components/app.js
js/components/bottom-panel.js
js/components/plates.js
js/components/sidebar-menu.js
js/components/sortable-densities.js
js/config.js
js/plates-model/model-worker.js
js/storage.js
package-lock.json
package.json
public/index.html

There is now a save button in the side menu, which stores the model in Firebase and displays a dialog showing information to restore the model. Models can be re-loaded by adding them as a URL param modelId.
@pjanik, I did end up implementing all the suggestions you brought up here: https://www.pivotaltracker.com/story/show/152380011. So, the 'saving' state now looks like the 'loading' state, and a dialog displays the model info. I also did some refactoring so that loading preset and cloud models work similarly. Let me know what you think!

Adds basic firebase saving and loading

---

js/components/bottom-panel.js
js/components/plates.js
js/plates-model/model-worker.js
package-lock.json

Pretty simple one.
I started implementing targetStepIdx as I did in 2D model:
https://github.com/concord-consortium/plate-tectonics/blob/master/js/plates-model/model.worker.js#L34-L37
A single step in 2D model was taking way longer, so it was useful there. But then I checked that simple approach works fine here, as a step calculation is faster.

Add step forward button

---

js/plates-model/field.js
js/plates-model/fields-collision.js

Here's the change for deforming the top plate - the modifier is a bit arbitrary, but a simple change otherwise

Deforming top plate in subducting zones

---

js/components/authoring.js
js/components/planet-wizard.js
js/components/sortable-densities.js
js/config.js
package-lock.json
package.json
test/components/sortable-densities.test.js
test/setup-tests.js

https://www.pivotaltracker.com/story/show/162387016
New option + text changes.
Also, I've updated test libs, added Enzyme lib, configured it and added the first unit test of a component.

Add a new option that removes "density| word from Planet Wizard

---

js/components/authoring.js
js/components/sidebar-menu.js
js/config.js
js/stores/simulation-store.js
test/components/sidebar-menu.test.js
test/components/sortable-densities.test.js
test/setup-tests.js

https://www.pivotaltracker.com/story/show/163766939
Adds a new checkbox and sidebar menu tests that also cover this new widget (+ old ones).

Add earthquakes toggle

---

js/config.js
js/plates-model/get-cross-section.js
js/plates-view/render-cross-section.js

That's the same PR as https://github.com/concord-consortium/tectonic-explorer/pull/46, but PR46 had a wrong base branch (another topic branch instead of master) and I forgot to change it to master before merging in.

Earthquakes cross-section

---

js/config.js
js/plates-model/earthquake.js

[#163915062]
Earthquakes should be guaranteed now to show up within the crust and lithosphere layer (and less magic numbers). Also, they shouldn't show up below trenches, as that didn't look good in the cross-section.

Tweak calculation of earthquake depth

---

js/components/authoring.js
js/components/sidebar-menu.js
js/config.js
js/stores/simulation-store.js
test/components/sidebar-menu.test.js

Added the option for volcanoes to authoring, to the sidebar, and to the store, similar to the recent changes made to add the Earthquakes to the map. This doesn't yet add volcanoes to the map.

Add volcanoes option

---

js/config.js
js/plates-model/earthquake.js
js/plates-model/field.js
js/plates-model/volcanic-eruption.js

Another PR that updates modeling of volcanic eruptions. Now, they are also based on the subduction intensity (relative speed of the colliding plates) and adds eruptions around the divergent boundary.
[#163915295]

Improve modeling of volcanic eruptions

---

css-modules/color-key.less
js/components/color-key.js
js/config.js
js/stores/simulation-store.js
test/components/color-key.test.js

Adding Earthquakes and Volcanic Eruptions to the key with a button to toggle the visibility of the key. Each section only appears if its corresponding UI setting is enabled, hence only see the Earthquake key if earthquakes are visible on the map.

Earthquakes and Volcanic Eruptions in the key

---

css-modules/sidebar-menu.less
js/components/planet-view.tsx
js/components/sidebar-menu.tsx
js/config.ts
js/plates-model/model-worker.ts
js/plates-model/model.ts
js/plates-model/plate-base.ts
js/plates-view/field-marker.ts
js/plates-view/plate-mesh.ts
js/stores/plate-store.ts
js/stores/simulation-store.ts

Add debug mode and plate visibility toggles

---

cypress/integration/basic/smoke-test.js
js/config.ts
js/plates-model/model-output.ts

Implement markCrossSectionFields option

---

js/plates-model/field.ts
js/plates-model/model.ts
js/plates-model/volcanic-activity.ts
js/plates-view/plate-mesh.ts

Demo:
http://tectonic-explorer.concord.org/branch/177681746-volcanic-act/index.html?preset=subduction
[#177681746]

Refactor volcanic activity, make volcanic arcs more realistic

---

js/plates-model/model-output.ts

It's mostly a debug feature I've used some time ago, but Tejal found an issue there, so let's get that fixed.
https://www.pivotaltracker.com/story/show/177727103

Fix markCrossSectionFields

---

js/plates-model/field.ts

[#178375945]
This PT story describes the issue and shows problems in provided screenshots:
https://www.pivotaltracker.com/story/show/178375945
It took me a while to understand the problem. They're kinda separate. `shouldPropagateBending` fixes case when two plates are merged together. Angle comparison and resetting bending progress (new line with `bendingProgress = 0`) handles issues around N and S pole.
You can compare:
https://tectonic-explorer.concord.org/branch/178375945-fix-trench-modeling/index.html?preset=subduction
with:
https://tectonic-explorer.concord.org/branch/master/index.html?preset=subduction

Fix trench modeling

---

js/plates-model/plate-draw-tool.ts

https://www.pivotaltracker.com/story/show/178804174
The previous implementation was more complicated and it wasn't setting up correctly the continental shelf while the continent was being erased. I've tried to simplify the implementation and fix this issue.

Reimplement plate draw tool, make it simpler and maintain continental shelfs

---

cypress/integration/basic/smoke-test.js
js/components/planet-view.tsx
js/config.ts

[#178415983]
A tiny PR that adds a new URL param.

Make time counter hidden by default, add URL param to show it

---

js/plates-model/model-worker.ts
js/plates-model/model.ts
js/stores/helpers/highlight-boundary-segment.ts

Rm model.getField and fix highlight boundary segment helpers

---

js/components/planet-wizard.tsx
js/stores/plate-store.ts
js/stores/simulation-store.ts

Simplify hot spots observing

---

css-modules/boundary-config-dialog.less

Following the specs and I think it makes it easier to notice arrows being added to the model.

Make boundary type dialog backdrop transparent

---

css-modules/rock-key.less
images/rock-key/svg/basalt-diagram.svg
images/rock-key/svg/gabbro-diagram.svg
images/rock-key/svg/high-grade-metamorphic-rock-diagram.svg
images/rock-key/svg/low-grade-metamorphic-rock-diagram.svg
images/rock-key/svg/mantle-brittle-diagram.svg
images/rock-key/svg/mantle-ductile-diagram.svg
images/rock-key/svg/medium-grade-metamorphic-rock-diagram.svg
js/components/rock-key.tsx
public/index.html

PT: [[#178642304]](https://www.pivotaltracker.com/story/show/178642304)
Demo: https://tectonic-explorer.concord.org/branch/rock-key-tweaks/index.html

Rock Key: tweak styling and update diagram image assets [#178642304]

---

js/colors/cross-section-colors.ts
js/plates-view/render-cross-section.ts

https://www.pivotaltracker.com/story/show/179940312

Update magma borders when metamorphism=false

---

js/stores/helpers/animation-utils.ts

[#180211076]
This PR fixes the issue found during QA: 
https://www.pivotaltracker.com/story/show/180211076/comments/227876105

Fix the camera reset button being stuck on the screen due to floating-point errors

---

cypress/integration/basic/simulation-rules/continental-collision.js
cypress/integration/basic/simulation-rules/divergentBoundary.js
js/plates-model/get-cross-section.ts
js/plates-model/volcanic-activity.ts
js/plates-view/render-cross-section.ts
test/plates-view/render-cross-section.test.ts

https://www.pivotaltracker.com/story/show/179940138
@kswenson, I've tried to explain updates in person. The model should make more sense now and be a bit simpler. I had to update Cypress tests that were checking the properties of fields with volcanoes.
The model should produce similar volcanic mountains chains. The new version is on the left side, the old one is on the right:

Magma that makes it all the way to the surface should solidify

---

js/plates-view/plate-mesh.ts
js/stores/simulation-store.ts

[#179943345]
This PR fixes a bug / missed UI specs: https://www.pivotaltracker.com/story/show/179943345/comments/227876972

Don't render plate velocity when rock patterns are shown

---

css/control-group.less
css/vcr-buttons.less
js/components/vcr-buttons.tsx

PT: [[#178645134]](https://www.pivotaltracker.com/story/show/178645134)
Demo: https://tectonic-explorer.concord.org/branch/button-styles/index.html?preset=benchmark
- tweak hover/active states
- eliminate redundant styles

Incorporate latest VCR button style changes

---

css-modules/sidebar-menu.less
css/bottom-panel.less
js/components/bottom-panel.tsx

PT: [[#180169391]](https://www.pivotaltracker.com/story/show/180169391) (in part)
Demo: https://tectonic-explorer.concord.org/branch/bottom-bar-styling/index.html?preset=benchmark
Adjust bottom bar flex containers so that bubbles rise above bar

Bottom bar styling

---

js/components/slider-switch.tsx

Fixes behavior of `<SliderSwitch>` component (used for the `Volcanoes` and `Earthquakes` switches on the bottom bar) on touch devices pointed out in review of #147.
Demo: https://tectonic-explorer.concord.org/branch/fix-touch-switches/index.html?preset=benchmark

Fix touch switches

---

css-modules/keys/rock-types.less
js/colors/cross-section-colors.ts
js/colors/rock-colors.ts
js/components/authoring.tsx
js/components/keys/rock-types.tsx
js/components/planet-view.tsx
js/components/side-container.tsx
js/config.ts
js/plates-view/planet-view.ts
js/plates-view/render-cross-section.ts

https://www.pivotaltracker.com/story/show/180330671
This PR includes three semi-related updates - commit names should describe them well. 
They're all related to TecRock and GEODE modes.
Note that GEODE mode is activated by adding ?geode URL param.

Add GEODE rock key, refactor color definitions, hide interaction buttons in TecRock, fix rock key visibility bug

---

css/planet-wizard.less
js/components/planet-wizard.tsx
js/components/simulation.tsx

[[#180395670]](https://www.pivotaltracker.com/story/show/180395670)

Adjust preset button positions when side container is open

---

js/stores/simulation-store.ts

PT: [[#180395432]](https://www.pivotaltracker.com/story/show/180395432)
Demo: https://tectonic-explorer.concord.org/branch/full-reload/index.html
@mklewandowski Let me know if a sync review would be helpful.

Reset camera, map type, and key visibility on reload button

---

js/plates-model/plate-draw-tool.ts

[#179940164
Old version of continent drawing:
A new one, implemented in this PR:
I've updated the distance function to use real distance instead of the number of fields between given field and the center.

Plate draw tool: make continent edges softer

---

js/stores/simulation-store.ts

Don't show key automatically when user opens cross-section

---

css/planet-wizard.less
js/components/planet-wizard.tsx
js/components/side-container.tsx
js/components/simulation.tsx

Do not show key button in Planet Wizard, simply PlanetWizard code

---

cypress/integration/basic/keysandoptions.js
cypress/integration/basic/smoke-test.js
cypress/support/elements/top-container.js
js/components/advanced-options.tsx
js/components/interaction-selector.tsx

Rename Rotate Camera to Rotate Planet

---

js/plates-model/crust.ts

[#181320915
This PR fixes issue shown below. These "lakes" behind the mountains were caused by rock layers that had negative thickness. It was really confusing, as the problem wasn't visible in the cross-section and only in the 3D view. First, I thought it was caused by the erosion code, but it was actually `subductOrFold` method. 
I've added `Math.min(1, ...)` each time where rock layer thickness was reduced. Also, I've added a simple test in functions that are most likely to detect this negative value.
https://user-images.githubusercontent.com/767857/154832794-83f1e377-34ec-4775-a929-aaa6bb2b62fd.mov
]

Fix issues in Crust class that could make some rock layers have negative thickness

---

js/config.ts
js/plates-model/plate-draw-tool.ts

Make shelf width configurable

---

js/plates-model/crust.ts
js/plates-model/field.ts
js/plates-model/volcanic-activity.ts
test/serialization-test-helpers.ts

Requirements are described pretty well in the PT story:
https://www.pivotaltracker.com/story/show/181256264
and there's a small update in the last comment:
https://www.pivotaltracker.com/story/show/181256264/comments/229772479
This PR adds thickening of overriding plate during subduction. This happens before large volcanic peaks are added because of the magma activity. See:

Add thickening of overriding plate during subduction

---

js/config.ts
js/plates-model/field.ts
js/plates-model/get-cross-section.ts

https://www.pivotaltracker.com/story/show/180993401

Increase size and elevation of the mid-ocean ridges

---

js/plates-model/crust.ts

https://www.pivotaltracker.com/story/show/181237555

Remove sandstone during volcanic activity

---

cypress/integration/basic/keysandoptions.js
js/components/keys/rock-types.tsx
js/config.ts
js/plates-model/volcanic-activity.ts

Make magma blobs properties configurable and update default values

---

js/plates-interactions/base-interactions-manager.ts

This PR fixes a bug that was nicely described here:
https://www.pivotaltracker.com/story/show/181137039

Fix interaction cursor handling

---

js/config.ts
js/plates-model/physics/forces.ts

Make orogeny strength configurable

---

css-modules/about-dialog.less
js/components/about-dialog-content.tsx
js/components/copyright.tsx

- information about Geode/TecRocks switch [[#181823028]](https://www.pivotaltracker.com/story/show/181823028)
- add additional NSF grant [[#181822908]](https://www.pivotaltracker.com/story/show/181822908)
- make about box content scrollable
Demo: https://tectonic-explorer.concord.org/branch/about-box/index.html?planetWizard=true

Update about box:

---

js/stores/helpers/boundary-utils.ts
js/stores/simulation-store.ts

PT: [[#180335792]](https://www.pivotaltracker.com/story/show/180335792)
Demo: https://tectonic-explorer.concord.org/branch/polar-boundary/index.html

Change polar cap boundary highlighting

---

js/plates-model/crust.ts
js/plates-model/get-cross-section.ts
js/plates-view/render-cross-section.ts

https://www.pivotaltracker.com/story/show/181127137
This PR makes accretionary wedge metamorphic.
Demo: https://tectonic-explorer.concord.org/branch/metamorphic-wedge/index.html?preset=subduction

Make accretionary wedge metamorphic

---

js/colors/rock-colors.ts
js/plates-model/crust.ts
js/plates-model/rock-properties.ts
js/plates-view/plate-mesh.ts
test/plates-model/crust.test.ts

PT: [[#181799207]](https://www.pivotaltracker.com/story/show/181799207)
Demo: https://tectonic-explorer.concord.org/branch/continental-sediment/index.html?rocks

Add thin layer of sediment to surface of continents [#181799207]

---

css-modules/keys/map-type.less
css-modules/side-container.less
js/colors/topographic-colors.ts
js/components/keys/crust-age-key.tsx
js/components/keys/map-type.tsx
js/components/side-container.tsx

PT: [[#180992934]](https://www.pivotaltracker.com/story/show/180992934)
Demo: https://tectonic-explorer.concord.org/branch/crust-age-key/index.html?rocks=true

Update crust age key [#180992934]

---

js/plates-view/render-cross-section.ts

PT: [[#182099435]](https://www.pivotaltracker.com/story/show/182099435)
Demo: https://tectonic-explorer.concord.org/branch/magma-sample/index.html?preset=subduction&rocks

Fix hit-testing of magma animations [#182099435]

---

css-modules/keys/map-type.less
css-modules/keys/rock-types.less
css-modules/side-container.less
images/plate-1-color.svg
images/plate-2-color-alt.svg
images/plate-2-color.svg
images/plate-3-color-alt.svg
images/plate-3-color.svg
images/plate-4-color.svg
images/plate-5-color.svg
js/components/keys/map-type.tsx
js/components/keys/plate-color-key.tsx
js/components/keys/rock-types.tsx
js/components/side-container.tsx

PT: [[#180992870]](https://www.pivotaltracker.com/story/show/180992870)
Demo: https://tectonic-explorer.concord.org/branch/plate-color/index.html?rocks&preset=benchmark

Update plate color key [#180992870]

---

images/rock-key/svg/intermediate-magma-diagram.svg
images/rock-key/svg/iron-poor-magma-diagram.svg
images/rock-key/svg/iron-rich-magma-diagram.svg

PT: [[#182239062]](https://www.pivotaltracker.com/story/show/182239062)

Update magma diagrams [#182239062]

---

css/cross-section.less
js/components/cross-section.tsx

PT: [[#181909786]](https://www.pivotaltracker.com/story/show/181909786)

Fix cursor over zoom buttons [#181909786]

---

js/colors/rock-colors.ts
js/plates-view/render-cross-section.ts

[[#182215316]](https://www.pivotaltracker.com/story/show/182215316)
Another attempt to div boundary rendering. I demoed that to Chris and Trudi today during the meeting about plate colors, and they seemed to be okay with this version.

Update divergent boundary fresh crust overlay

---

css-modules/keys/elevation-descriptions.less
css-modules/keys/elevation-labels.less
js/components/keys/elevation-descriptions.tsx
js/components/keys/elevation-key.tsx
js/components/keys/elevation-labels.tsx

Add spaces to elevation labels.

Update elevation labels

---

js/plates-view/render-cross-section.ts

[#179785717]
This PR fixes a bug found by Saravanan:
https://www.pivotaltracker.com/story/show/179785717/comments/231400243

Stop magma animation when subduction zone becomes inactive

---

css-modules/side-container.less

[[#182284419]](https://www.pivotaltracker.com/story/show/182284419)

Fix Keys and Options close button

---

js/components/authoring.tsx
js/config.ts
js/plates-model/crust.ts
js/plates-view/plate-mesh.ts
js/plates-view/render-cross-section.ts

This PR addresses a few smaller stories that requested new URL parameters. Each commit corresponds to one PT story.

Add new URL parameters

---

js/plates-model/crust.ts

Remove continental crust when volcanic rocks are added

---

js/colors/cross-section-colors.ts
js/components/keys/rock-types.tsx
js/plates-view/render-cross-section.ts

https://www.pivotaltracker.com/story/show/179578139
This PR changes linear interpolation to 3 discrete colors that we use in the Rock Key. Interpolation didn't work that well as no one could recognize that colors were actually changing. This looks more clear.

Update magma blob coloring

---

js/plates-model/get-temp-and-pressure.ts

This PR fixes an issue described precisely in the PT story:
https://www.pivotaltracker.com/story/show/183128285

Update subduction medium grade metamorphic rock pressure

---

js/config.ts

[#183678637]
A simple update of the default config value.

Disable plate division

---

js/plates-model/crust.ts
test/plates-model/crust.test.ts

[[#183763493]](https://www.pivotaltracker.com/story/show/183763493)
This PR removes continental sediments from the continental shelf. PT story has a nice description and screenshot that shows the affected area.

Remove continental sediments from continental shelf

---

js/components/relative-motion-stopped-dialog.tsx

[#183681490]
A small change to address the issue found by Saravanan:
https://www.pivotaltracker.com/story/show/183681490/comments/234509311

Handle preset case in the relative motion stopped dialog

---

css-modules/data-saving-dialog.less
js/components/data-saving-dialog.tsx
js/components/draggable-dialog.tsx
js/components/simulation.tsx
js/stores/simulation-store.ts
js/types.ts

[#184074513]
Demo:
https://user-images.githubusercontent.com/767857/209190660-90ace332-258c-4077-82d9-0dfe9d247d6b.mov

Add data saving dialog

---

js/stores/simulation-store.ts

Prevent navigation in Activity Player while data is being saved

---

js/plates-view/render-cross-section.ts

Add data sample pin numbers

---

packages/tectonic-explorer/js/components/authoring.tsx
packages/tectonic-explorer/js/config.ts

[[#184185532]](https://www.pivotaltracker.com/story/show/184185532)
Small PR that updated authoring page.

Update authoring page, let authors configure dataSampleColumns

---

packages/shared/data-sample-info.tsx
packages/shared/data-sample-to-table-row.tsx
packages/shared/types.ts
packages/tectonic-explorer/js/components/data-collection-dialog.tsx
packages/tectonic-explorer/js/plates-interactions/cross-section-interactions-manager.ts
packages/tectonic-explorer/js/plates-view/render-cross-section.ts
packages/tectonic-explorer/js/stores/simulation-store.ts

Add pin number to table, fix ordering of data samples

---

packages/tecrock-table/src/components/runtime.tsx
packages/tectonic-explorer/js/stores/simulation-store.ts

[#184074513]
This PR addresses the comment made by Saravanan and then confirmed by Trudi:
https://www.pivotaltracker.com/story/show/184074513/comments/235006523
Data should be cleared immediately after user confirms that they want to restart data collection.

Clear data samples immediately after user confirms that he wants to restart data collection

---

packages/tectonic-explorer/js/plates-view/cross-section-3d.ts

This PR fixes / workarounds issue described here: [[#184137645]](https://www.pivotaltracker.com/story/show/184137645)
The problem is quite tricky. The 3D cross-section code was making an assumption that front and back wall have the same dimensions/width. This is not true due to the nature of the spherical globe surface. Often, back wall is shorter when measured in kilometers, but it's rendered with the same width.
That leads to issues observed by Saravanen. It also affects the rock picker tool which will show a different rock that you're pointing when you try to pick something on the right side of the back cross-section wall.
The proper fix would be to use custom buffer geometries for all the cross-section walls and construct a 3D trapezoid. But it didn't seem realistic with the time I …

Workaround issue caused by the fact that 3D cross-section is not a cube, but trapezoid

---

packages/tecrock-table/src/components/runtime.scss

[[#184249537]](https://www.pivotaltracker.com/story/show/184249537)

TecRock Table: update layout so snapshots are bigger when possible

---

packages/tectonic-explorer/css-modules/data-collection-dialog.less

[[#184247190]](https://www.pivotaltracker.com/story/show/184247190)

Tectonic Explorer: update notes style

---

.npmrc
package.json

chore(npm): Add "engines" & 'engine-strict'

---

packages/tecrock-simulation/src/colors/rock-colors.ts
packages/tecrock-simulation/src/config.ts
packages/tecrock-simulation/src/plates-model/get-cross-section.ts
packages/tecrock-simulation/src/plates-view/render-cross-section.ts

This PR updates the look of gradient around the divergent boundary. More details and link to Ryan's video posted on Slack in the PT story: https://www.pivotaltracker.com/story/show/186640790

Update divergent boundary gradient

---

packages/tecrock-simulation/src/plates-model/get-cross-section.ts
packages/tecrock-simulation/src/plates-view/render-cross-section.ts

This PR addresses a bug described here:
https://www.pivotaltracker.com/story/show/186640790/comments/239865995
I commented out some logic earlier while experimenting with this gradient (initial work on this story).

Fix a bug causing a red gradient to appear around continental divergent boundaries

---

package-lock.json
packages/tecrock-simulation/package.json
packages/tecrock-simulation/src/storage.ts
packages/tecrock-simulation/src/stores/simulation-store.ts

This is phase one of the migration of the models to S3.  In this phase new models are saved to S3 using the Token Service and loaded from S3 with a fallback to loading from Firebase when they are not found on S3.
Test links:
- New model saved to S3: https://tectonic-explorer.concord.org/branch/move-models-to-s3/index.html?modelId=Q316ZpnzqaNUeG24tvRD&rocks=false
- Old model manually migrated to S3: https://tectonic-explorer.concord.org/branch/move-models-to-s3/index.html?modelId=08971159-a0b4-4b02-aead-29719faf4e64&rocks=false
- Old model not migrated to S3, will fallback to Firebase: https://tectonic-explorer.concord.org/branch/move-models-to-s3/index.html?modelId=d9ac2f07-d093-4b5e-8f14-2a8330921614&rocks=false

feat: Change save/load of models to use S3 [TE-2]

---

package-lock.json
packages/tecrock-simulation/package.json
packages/tecrock-simulation/src/storage.ts
packages/tecrock-simulation/src/stores/simulation-store.ts

All models are now loaded/stored on S3.

feat: Remove model load fallback to Firebase [TE-5]
