concord-consortium/tectonic-explorer

js/components/authoring.js, js/config.js
Density-setting is now hidden unless the URL parameter 'setDensities' is passed. This means conditionally hiding the step in the bottom bar, and skipping it after step 3. I held off on introducing an elegant way to hide additional steps, but if we added a second configurable step it's probably worth looking into.
=> Adding density-setting as a configurable parameter

js/components/authoring.js, js/components/plates.js, js/config.js, js/plates-model/model-worker.js
Previously, going back from the force step to the drawing step would not remove added forces. Now, a snapshot is stored whenever the "next" button is pressed, and one is restored whenever the "back" button is pressed. This will make "undoing" steps like the force drawing simpler in the future.
=> Back button stores snapshots between steps

css/cross-section-3d.less, css/plates.less, css/react-toolbox-theme.less, js/components/cross-section-3d.js, js/components/plates.js, js/components/small-button.js, js/plates-view/cross-section-3d.js, js/plates-view/view-3d.js, package-lock.json
This PR adds reset camera buttons for the main view and the cross-section view.
I was going back and forth and I wasn't sure if we should keep the state of the cross-section camera reset in the main component or in the CrossSection3D. I implemented both and decided the latter makes more sense. First, it's pretty UI-specific state and I don't think that it's crucial for the app to know it (even if we used Redux or MobX). Second, `CrossSection3D` already contains camera-related state in the canvas views. So, I think that self-contained component makes more sense.
Also, I think that probably it would be nice to refactor `Plates` component and separate out main 3D view component, so it's similar to the `CrossSection` component.
=> Add reset camera buttons for the main view and the cross section view

css/planet-wizard.less, css/sortable-densities.less, js/components/sortable-densities.js
@pjanik, re: the discussion [here](https://www.pivotaltracker.com/story/show/152289874), these are the changes I made to improve the UI of the density picker. Like Amy pointed out, this doesn't do much in terms of scaling on different devices, but I'm not sure the best way to handle that. In Geniverse, we just applied a scale factor on top of the whole page, but I realize you've made GEODE more responsive, so I'm curious what your thoughts are.
Specifically, the changes are: adding a hamburger menu and changing cursor to indicate drag-ability. Also adding helper text.
=> Making drag interface on density sorter more obvious

js/config.js, js/plates-model/add-relative-motion.js, js/plates-model/divide-plate.js, js/plates-model/model-output.js, js/plates-model/model.js, js/plates-model/plate-base.js, js/plates-model/plate-draw-tool.js, js/plates-model/plate.js, js/plates-model/subplate.js, js/plates-model/volcanic-activity.js, test/model-serialization.test.js
Adds a new config option: `enforceRelativeMotion`. When it's true (default), the model will make sure that there's some relative motion between plates. Also, big plates (bigger than `config. minSizeRatioForDivision`) will be split into two smaller plates.
=> Enforce relative motion between plates and break big plates into smaller chunks

js/components/sidebar-menu.js, js/components/sortable-densities.js
This PR fixes problem that Sarah has discovered. She had troubles running this URL:
http://models-resources.concord.org/plate-tectonics-3d/branch/master/index.html?planetWizard&planetWizardSteps=%5Bdensities%5D&modelId=03639ca9-8f84-46c0-8b4c-3ae2f893813e&playing=false&crossSection3d=false
`planetWizardSteps=[denisties]` was causing issues as the density selector was the first step.
Console error was easy to fix - JS is complaining about .reduce call without the second argument, as it's called for an empty array. That's fixed by a new helper function `minKey`.
But the component still didn't work after fixing that. The problem was that it was initially called with an empty object (before the model was loaded), and when real properties were set (after the model was loaded) the component …
=> Fix densities selector

js/config.js, js/plates-model/add-relative-motion.js, js/plates-model/model.js, js/plates-model/volcanic-activity.js, js/seedrandom.js, package-lock.json, package.json, test/model-serialization.test.js, test/seedrandom.test.js
Add a new 'deterministic' option to config and ensures that model behaves in a deterministic way when it's set to true. It also works with model saving and loading, as the current seedrandom state is being serialized.
=> Seed random behaviour, add 'deterministic' option (+ add / update tests)

js/plates-model/field.js, js/plates-model/plate-draw-tool.js
It was an obvious bug after ocean depth has been changed. I tried to make sure that in the future we don't have to worry about it. Also, I'm resetting other properties as it seems right and might help with weird effects observed by Amy and Trudi ("phantom plates" after erasing continents).
=> Reset field properties after changing its type using draw / erase tool

js/plates-model/field.js, js/plates-model/plate-draw-tool.js
Relatively simple change - I factored out the logic for drawing a tile, and draw a slightly lower tile on the first tile which is too far to draw an actual continent. This means that the drawn area is now slightly larger than before. I could have lowered the max `distance` from 7 to counteract this, but the behavior seems fine so I did not. 
The only complication was making sure that the max continent to plate ratio was maintained. Right now, you can overwrite the continental shelf once you hit the ratio, but I think that's mostly an edge case
=> Leaving a border of lower elevation around drawn continents

js/config.js, js/plates-model/fields-collision.js, js/plates-model/model.js
[#157605459]
Make continent-continent collisions more likely. When two continent buffers are colliding, we know that it's not continent-ocean collision case (where we want to spot plates), but rather continent-continent (where we want collision to happen).
=> Improve continent buffers handling

js/components/app.js
What do you think of a fix like this for the default wizard, @pjanik? I think the extra reload adds a fraction of a second to the load time, which barely noticeable but not ideal. Perhaps I should be trying to modify the config instead?
=> Making the blank planet wizard load by default

.gitignore, js/plates-model/subduction.js, js/stores/simulation-store.js, package.json, test/model-serialization.test.js, test/plates-model/model.test.js, test/plates-model/subduction.test.js, test/setup-tests.js
[#163767335
I didn't end up adding as many tests as I hoped. But I added some for Subduction class, perhaps setting the pattern how to interact with fake field object. I guess upcoming work will use mostly this helper, so there are some examples at least.
I actually spent some time updating babel, presets, plugins, and also ThreeJS, and refactoring some code that had been copy-pasted (peels dir):
https://github.com/concord-consortium/tectonic-explorer/commit/8d990665c563486cf21d45a12866ede21ec6694f
https://github.com/concord-consortium/tectonic-explorer/commit/3a68512379d17c384cdeace4d06bae73a82c556e
etc.
ThreeJS update is important, as we have custom shaders that depend on its internals, and falling too far behind might get problematic. These changes are already in master, as it was 100% …
=> Add more unit tests

js/config.js, js/plates-model/field.js, js/plates-model/model-output.js, js/plates-view/earthquake-texture.js, js/plates-view/earthquakes.js, js/plates-view/planet-view.js, js/plates-view/plate-mesh.js, js/plates-view/temporal-events.js, js/stores/field-store.js, js/stores/simulation-store.js
Note that this PR is open against https://github.com/concord-consortium/tectonic-explorer/pull/43 as it was based on it.
It adds initial rendering of the earthquakes, following the same shape and style as one used in Seismic Explorer. I've tried to make sure that the code can be reused for volcanoes.
Note that earthquakes are disabled by default and you need to add `earthquakes=true` URL param.
Demo:
http://tectonic-explorer.concord.org/branch/162386261-earthquakes-rendering/index.html?preset=subduction&earthquakes=true
=> Earthquakes rendering

js/config.js, js/plates-model/get-cross-section.js, js/plates-view/render-cross-section.js
This initial work will render the earthquakes in cross section view and display them at relative magnitude sizes. The depth calculation may need to be changed at the earthquake level or pending review feedback on how to interpret the data. There is currently an issue with rendering the quakes when using the subduction preset (?preset=subduction&debugCrossSection=true&earthquakes=true) showing them below and to the left of where the top plate meets the subducting plate
=> Earthquakes cross-section

js/config.js, js/plates-model/earthquake.js, js/plates-model/get-cross-section.js, js/plates-model/model-output.js, js/plates-model/volcanic-eruption.js, js/plates-view/earthquake-helpers.js, js/plates-view/plate-mesh.js, js/plates-view/render-cross-section.js, js/plates-view/temporal-events.js, js/plates-view/volcanic-eruption-helpers.js
Changes:
1. Volcanic eruptions are now being rendering in cross-section view
2. Eruptions symbol are pointing north (requested by Sarah)
3. Eruptions symbol color is now configurable (so Amy and Sarah can play with it)
4. Fixed a bug that was causing timestep change to generate a different number of earthquakes and eruptions
5. Fixed a bug that was causing earthquakes and eruptions always being rendered in the cross-section (regardless of the side menu settings)
=> Volcanoes and earthquakes updated

cypress/integration/gpu-dependant/canvas.js
Rework of the pixel color test to run via a preset model instead of hand-drawn continents so that the colors are more predictable.
This also switches to using the Hue of a pixel instead of manually attempting to work out RGB ranges for land, sea, etc.
=> Canvas color test

css/cross-section-3d.less, css/planet-view.less, js/components/sortable-densities.tsx, js/stores/simulation-store.ts, package-lock.json, package.json, test/components/sortable-densities.test.tsx
This PR fixes Step 4 in the planet wizard:
https://tectonic-explorer.concord.org/branch/master/index.html?planetWizard=true
If you get there, you should notice that densities are draggable, but once dragging stops, they always go back to their initial positions.
Also, there's a tiny fix that removes canvas outline. When user clicks anywhere in the main view or cross-section, a blue outline is added. It doesn't seem useful, so I just removed that.
=> Fix density selector UI and remove canvas outline

css/planet-view.less, js/colormaps.ts, js/components/color-key.tsx, js/components/sidebar-menu.tsx, js/config.ts, js/cross-section-colors.ts, js/plates-model/crust.ts, js/plates-model/field.ts, js/plates-model/model-output.ts, js/plates-model/model-worker.ts, js/plates-view/plate-mesh.ts, js/plates-view/render-cross-section.ts, js/stores/field-store.ts, js/stores/simulation-store.ts
This PR lets users change color scheme (using menu) in 3D view and show the top rock layer. Demo:
https://tectonic-explorer.concord.org/branch/177477605-rock-3d/index.html?preset=subduction
Note that this PR nicely predents how to transfer new property from Web Worker to the main thread.
The new array is added in `model-output.ts` and then it's handled in `field-store.ts` while this class is processing post message from the worker. 
I changed `Rock` enum to use numbers, as that lets us transfer values easily using post message transferrable properties (Int16Array). String can't be transported that way.
=> Render the top rock layer in 3D view

js/colormaps.ts, js/components/color-key.tsx, js/config.ts, js/peels/sphere/to-cg.ts, js/plates-model/grid.ts, js/plates-model/model-output.ts, js/plates-view/cross-section-markers.ts, js/plates-view/planet-view.ts, js/plates-view/plate-label.ts, js/plates-view/plate-mesh-fragment.glsl, js/plates-view/plate-mesh-vertex.glsl, js/plates-view/plate-mesh.ts
Demo links:
- default settings - 64 topo shades, flat shading, bump mapping ON: https://tectonic-explorer.concord.org/branch/177509275-elevation-3d/index.html?preset=subduction
- same, but with bump mapping OFF - cleaner / more cartoon-like style: https://tectonic-explorer.concord.org/branch/177509275-elevation-3d/index.html?preset=subduction&bumpMapping=false
- same, but also without flat shading: https://tectonic-explorer.concord.org/branch/177509275-elevation-3d/index.html?preset=subduction&bumpMapping=false&flatShading=false
- “realistic” settings - 256 topo shades, no flat shading, bump mapping ON: https://tectonic-explorer.concord.org/branch/177509275-elevation-3d/index.html?preset=subduction&topoColormapShades=256&flatShading=false
You can compare that with old way of rendering: …
=> Render elevation in the 3D view

js/colormaps.ts, js/plates-model/crust.ts, js/plates-model/field.ts, js/plates-model/subduction.ts, js/plates-view/planet-view.ts
I've ended up with relatively simple implementation.
`subduction.progress` is replaced with more general `bendingProgress` attribute, which is defined for each field. That way plate can bend even before subduction happens. It's done in `propagateBending` method. There are also some tweaks to wedge to cover unwanted break between the wedge and the top plate (it could create an impression that it's the deepest part of the ocean).
=> Add trench modeling

js/colormaps.ts, js/config.ts, js/cross-section-colors.ts, js/plates-model/field.ts, js/plates-model/get-cross-section.ts, js/plates-model/model-output.ts, js/plates-view/cross-section-3d.ts, js/plates-view/render-cross-section.ts
Old cross-section:
⬇️ ⬇️ ⬇️
New cross-section:
The magma animation is done in a very simple way, but it works. An obvious use case where animation would be twice as fast is if the user was looking at two divergent boundaries at the same time. But it almost never happens in practice, as the cross-section line is too short.
Also, there are some small tweaks of rock colors requested by Stephanie.
=> Update rendering of magma around divergent boundaries

js/plates-model/crust.ts, js/plates-model/field.ts, js/plates-model/volcanic-activity.ts, js/plates-view/render-cross-section.ts, test/plates-model/crust.test.ts, test/plates-view/render-cross-section.test.ts
This PR changes the way how rock layers are rendered. You can compare the screenshots below.
The main difference is that rock layers shouldn't have jagged edges anymore. CS rendering will interpolate between various layers. However, this requires all the rock layers to have a defined, specific order. So, sediments will always be the topmost layer, then rhyolite, etc, down to granite or gabbro. Only then I can connect rock layers between neighboring fields. Otherwise, if layers are totally mixed, we'd get crossing lines. But this constraint seems to be fine, there's no use case where layers should have a different order. 
Another changes in this PR:
- Mountain roots are formed in a different way to avoid the impression that volcanic rocks are "sinking" and getting lower than the initial …
=> Update rock layers rendering, mountain roots forming + small refactoring

js/plates-model/crust.ts, js/plates-model/field.ts, js/plates-model/model.ts, js/plates-model/plate.ts, package.json, test/model-serialization.test.ts, test/plate-division-merge.test.ts, test/serialization-test-helpers.ts
It's a similar test to the one used by the serialization method.
The idea is to have two models, make a set of actions in one of them, make sure these actions bring it to the initial state, and finally run both models for some time and check if they stay identical.
=> Refactor model methods related to plate merge and division, add automated tests of these functionalities

js/plates-model/get-cross-section.ts, js/plates-view/render-cross-section.ts
This PR fixes (or at least greatly improves) issues described here:
https://www.pivotaltracker.com/story/show/178804156
Changes:
1. I've improved a bit `debugCrossSection` mode to show plate number for each rock column.
2. Some of the cases I've traced were related to the fact that `.dist` property of cross-section fields was not calculated correctly (after some plate chunks got merged together). It's probably confusing, but each field has three properties: distStart, dist, and distEnd. distStart and distEnd describe how wide is a given field in the cross-section view. `dist` is something that is finally used by the rendering code. Each field is reduced to a single point, as we don't want to render columns. Insteady, we find a center of each field and connect them. So, `dist` will usually …
=> Fix cross-section calculations

cypress/integration/basic/simulation-rules/island-collision-2.js, cypress/integration/basic/simulation-rules/subduction.js, js/config.ts, js/plates-model/grid.ts, js/plates-model/model-worker.ts, js/stores/simulation-store.ts, test/integration/model-serialization.test.ts, test/integration/plate-division-merge.test.ts
The most time-consuming thing is the creation of the `Grid` singleton instance that includes `VoronoiSphere` calculations. Voronoi Sphere is used to find a field that is closest to a specified position. It's useful for collision detection and a few other core parts of the model. This PR does two things:
- Creates `Grid` instance in an optimal moment both in web worker and the main thread.
- Sets an optimal Voronoi sphere field number based on the number of model fields. This number will be 5 times bigger than the number of model fields. The default grid has around 10000 fields, so the Voronoi sphere will have around 50k. The previous value was hardcoded to 200k which seemed to be too much. I've tested the model both with 200k and 50k fields and couldn't see a significant difference.
=> Improve loading performance

.eslintrc.js, js/components/rock-images.tsx, js/plates-model/model-worker.ts, js/stores/helpers/boundary-utils.ts, js/stores/plate-store.ts, js/stores/simulation-store.ts, js/types.ts, js/worker-controller.ts
Extends the existing boundary utilities with some functions required by the dialog code:
- `highlight-boundary-segment.ts` renamed to `boundary-utils.ts`
- `getBoundaryInfo()` added to `boundary-utils.ts`
- `getBoundaryInfo()` removed from `model-worker.ts`
- `isPolarCap` added to `PlateStore`
=> Extend boundary utilities to support boundary assignment dialogs

js/components/cross-section-3d.tsx, js/components/planet-view.tsx, js/stores/simulation-store.ts
This PR fixes two bugs found during QA.
https://www.pivotaltracker.com/story/show/177652612/comments/227721882:
> If the key is manually closed and then the rock sample is then taken, should we expect the key to reopen? currently it doesn't and as per the description it seems like it should.
https://www.pivotaltracker.com/story/show/180051337/comments/227722170:
> With take sample enabled, if the cross section is closed and reopened, we lose the take sample setting and the rock sample marker is no longer displayed but even with this normal cursor we are able to take the rock samples and the key updated accordingly. This seems like a bug.
=> Rock Sample tool bug fixes

js/components/boundary-config-dialog.tsx, js/geo-utils.ts, js/stores/helpers/boundary-utils.ts, js/stores/simulation-store.ts, js/types.ts
This PR adds the math necessary to set force vectors using boundary type info. It might seem weird to keep fields in the `BoundaryInfo` instead of plates, but they provide more data than just the `plateId` (=> absolute position useful to calculate forces later). At the same time, they're defining `plateId` too.
=> Set hot spots / force vectors based on the boundary type

js/components/simulation.tsx, js/stores/helpers/boundary-utils.ts, js/types.ts
[#179577787]
This PR adds calculations of the boundary type using existing hot spots and boundary orientation. I've used the dynamic approach, as it's reasonably easy with the orientation already calculated.
The nice side effect of that sometimes you can get information whether the given boundary is convergent or divergent even when you click on it for the very first time (if you set up neighbouring plates correctly).
=> Calculate boundary type

js/stores/helpers/boundary-utils.ts, js/stores/simulation-store.ts
This PR improves our heuristic for determine which plate is on which side of a longitudinal boundary segment. ~~It works _most_ of the time, but can still give incorrect results when the longitude values wrap between the boundary and the center of the plate. With our existing presets this code gives the correct results on all longitudinal boundaries except the 4/5 boundary in the uneven five-plate preset with the globe rotated. @pjanik may have a better idea for how to address this.~~
I figured out a better approach.
=> Fix longitudinal boundary assignment under rotation

css-modules/boundary-config-dialog.less, js/components/boundary-config-dialog.tsx, js/components/planet-view.tsx, js/components/planet-wizard.tsx, js/components/simulation.tsx, js/plates-interactions/base-interactions-manager.ts, js/plates-interactions/helpers.ts, js/plates-interactions/planet-click.ts, js/stores/simulation-store.ts, js/types.ts
Positions the boundary assignment dialog above and to the right of the location of the click rather than in the center of the screen, so that it is less likely to cover up the boundary the user is interested in as well as the force arrows. Prevents the dialog from being dragged out of the visible area. Also tweaks the styling to match the spec better.
Demo: https://tectonic-explorer.concord.org/branch/boundary-dialog-position/index.html
=> Offset initial dialog position; keep dialog in bounds when dragging

js/plates-view/plate-mesh-fragment.glsl, js/plates-view/plate-mesh-vertex.glsl, js/plates-view/plate-mesh.ts
Copying my message from Slack as it might be useful if I ever want to revisit this feature:
> At this point, I’m pretty sure that it’s almost impossible to implement it 100% correctly because of some specifics how GPU work. I’ll try to explain that as simple as possible (might not be necessary for most of the people here, but maybe useful even for me if I ever go back to this issue and forget what was the problem ;)). You can imagine that each vertex in our 3D mesh is a model field. 3 vertices create a triangle, and all triangles together create a 3D globe we can see. We can specify which pattern texture should be used for each vertex of this triangle, but we’re not able to specify which texture should be used for all the pixels between these vertices (=> triangle “body”). GPU does it …
=> Add rock patters to the globe view

js/stores/simulation-store.ts
[#179577787]
This was happening when the user wasn't closing the boundary type dialog, but moving his mouse straight to "Next" button.
=> Fix a bug that was sometimes leaving the boundary highlighted forever

js/colors/rock-colors.ts, js/components/color-key.tsx, js/config.ts, js/plates-view/render-cross-section.ts
[#179943345]
Now, when we render rock patterns in the 3d view, I think it doesn't make sense to keep the hex color of the rocks. It's additional maintenance and they're already out of sync with the patterns. 
Also, I've updated the key to show rock key when colormap == rock.
=> Remove rock colors, update key to handle colormap == rock

js/plates-interactions/base-interactions-manager.ts, js/plates-interactions/cross-section-click.ts, js/plates-interactions/cross-section-drawing.ts, js/plates-interactions/force-drawing.ts, js/plates-interactions/helpers.ts, js/plates-interactions/planet-click.ts
https://www.pivotaltracker.com/story/show/180230314
There are two instances of interaction managers - one for the planet view and one for the cross-section. Recently, I've moved event handlers from canvases to document. This was breaking interactions in some edge cases, depending on the timing of MobX observers. For example, the cross-section manager could remove all the event handlers from document **after** the planet view manager just added its own handlers.
Also, I've fixed cursors handling. Using document was causing similar issues, so I've limited custom cursor to canvas that is unique per manager.
=> Fix bugs related to interactions and cursors

css-modules/slider-switch.less, css/bottom-panel.less, js/components/bottom-panel.tsx, js/components/sidebar-menu.tsx, js/components/slider-switch.tsx, test/components/sidebar-menu.test.tsx
PT: [[#180019424]](https://www.pivotaltracker.com/story/show/180019424)
Demo: https://tectonic-explorer.concord.org/branch/volcanoes-earthquakes/index.html?preset=benchmark
Presence/absence of switches is controlled by authoring (same as before)
Clicking on any part of switch changes the polarity of the switch
Thumb can also be dragged from one end to the other
=> Add earthquakes/volcanic eruption switches to bottom bar

css-modules/map-type-button.less, js/color-maps.ts, js/components/authoring.tsx, js/components/bottom-panel.tsx, js/components/map-type-button.tsx, js/components/planet-wizard.tsx, js/config.ts, js/stores/simulation-store.ts, test/utils.test.ts
This PR attempts to wrap up a number of outstanding PT stories:
[[#180169391]](https://www.pivotaltracker.com/story/show/180169391) TecRocks model bottom bar UI
[[#180168841]](https://www.pivotaltracker.com/story/show/180168841) GEODE Bottom Bar UI
[[#180256803]](https://www.pivotaltracker.com/story/show/180256803) Authoring control of available map types
Demo (TecRocks): https://tectonic-explorer.concord.org/branch/geode-param/index.html?preset=benchmark
Demo (Geode): https://tectonic-explorer.concord.org/branch/geode-param/index.html?geode&preset=benchmark
Demo (Authoring): https://tectonic-explorer.concord.org/branch/geode-param/index.html?authoring
Notable features:
- new `geode` url parameter controls whether the TecRocks or Geode UI is presented
- `geode` planet wizard uses prior …
=> Support geode url param; update authoring

js/components/authoring.tsx, js/components/sidebar-menu.tsx
From a comment in [this PT story](https://www.pivotaltracker.com/story/show/180168841):
>I also noticed that the "Metamorphism" check box was available in the menu in the link provided below. That should not be in the GEODE version. Can you remove it?
Testable at https://tectonic-explorer.concord.org/branch/no-geode-metaphorphism/index.html?geode&preset=benchmark.
=> Eliminate metamorphism option from authoring and sidebar in geode

package-lock.json, package.json
For as-yet-unknown reasons, the update to `css-loader` v6 broke the rendering of the fullscreen icon button. In lieu of investigating we simply revert to `css-loader` v5 for now.
Demo: https://tectonic-explorer.concord.org/branch/css-loader-5/index.html?preset=benchmark
=> Fix fullscreen icon button

js/components/authoring.tsx, js/config.ts
There were two issues related to autocomplete:
- "metamorphic" value was not handled correctly for "sidebar" array and Geode/TecRock mode, so it was possible to remove it from the TecRock version
- array values were compared unsorted that could lead to unnecessary URL arguments
First, I've tried to handle it in a more generic way (by filtering autocomplete options dynamically rather than storying them in state and modifying explicitly) and then refactor other pieces that use a similar approach. But I ran into issues and just gave up to save time. Especially that other pieces are more complicated than sidebar. After working on this, I have an impression that it might become pretty confusing if we add more Geode options (I had hard times finding out what's going on, even though the issue …
=> Authoring: fix handling of autocomple options, fix sidebar options in Geode mode

css-modules/side-container.less, css/variables.less
A small fix to address layout issues when scrollbars are visible:
https://www.pivotaltracker.com/story/show/179940030/comments/228127468
(probably on windows + mouse)
[#179940030]
=> Rock key: update styles to make enough space for scrollbar

js/components/advanced-options.tsx, js/components/bottom-panel.tsx, js/components/planet-wizard.tsx, js/components/side-container.tsx, js/components/sortable-densities.tsx, js/components/top-bar.tsx, js/log.ts, js/plates-interactions/cross-section-drawing.ts, js/stores/simulation-store.ts, package-lock.json, package.json
[#178132549]
I've wrapped the lara-interactive-api `log` function in a custom wrapper defined at `js/log.ts`. The main goal of that was to enforce self-documentation using types. It won't be possible to add a new event without documenting it using a new type. I'm planning to provide a link to `js/log.ts` to the project team, so they can always check all the available log messages. I'm trying to keep this file minimal and readable for non-programmers. If I use some external type, I'm adding a comment that lists possible values.
We also have a google spreadsheet with log events that I can't find now. But once I do, I think I'll just copy there a link to this file too. I think this is a more maintainable approach long-term than keeping a separate spreadsheet list.
=> Add LARA / AP logging

css-modules/keys/rock-types.less, js/components/keys/rock-types.tsx
[#180480249]
I've added 250ms delay to flash animation so there's time for the container to scroll. Sometimes it's necessary, sometimes not, but 250ms seems to be a good compromise. As even if scrolling isn't necessary, it doesn't feel too strange.
=> Rock key: scroll selected rock into view

js/components/planet-wizard.tsx
[[#180479948]](https://www.pivotaltracker.com/story/show/180479948)
I was going back and forth here, but I think the cleanest solution to address request in this PT story is just to never reset/unload user changes. Unless he goes to the very initial step (layout selection). That makes implementation and behavior clean.
=> Planet Wizard: keep user changes while he navigates between steps

cypress/integration/basic/smoke-test.js, package-lock.json, package.json
Well, it took a few attempts, but I think failures were caused by the fact that now the reload button has a small delay before page refresh is executed (logging). So, we're triggering the click, but sometimes cypress was starting to check the existing DOM too soon (before reload happened).
=> Fix smoke test

js/plates-model/get-cross-section.ts
https://www.pivotaltracker.com/story/show/179785302
PT story can be a bit confusing. Generally, the project team didn't like "cliffs" visible sometimes. It turns out it was mostly happening when the accretionary wedge was "pressed into" the subducting plate. It's visible below - red line shows the wedge, and green one shows where it's supposed to be:
This issue was happening only when the subducting plate was drawn from right to left. Left to right was working just fine.
It was caused by the function that smoothes out the subducting plate. This function tries to find which fields should be averaged. Sometimes it was including fields that didn't subduct yet. This doesn't work well when there's an accretionary wedge.
I didn't notice this issue before, as when we're starting processing from …
=> Apply interpolation only to fields that are subducting not to interpolate accretionary wedge

js/components/planet-view.tsx, js/components/planet-wizard.tsx, js/components/side-container.tsx, js/components/simulation.tsx, js/stores/simulation-store.ts
This PR fixes issue pointed out by Saravanan (see the original [comment](https://www.pivotaltracker.com/story/show/180480267/comments/229323808)).
He noticed that the earthquakes caveat is being displayed in the Planet Wizard. This should not happen anymore. I also realized we didn't reset most of the options on model reload. So, the user could go to advanced options, turn on things like wireframe rendering, and he'd be stuck with it in the Planet Wizard mode after reload (aka "plate reset"). There's no clear answer if we should reset all the UI options or not, but it definitely feels safer, as it's less likely users will be stuck with a config that isn't working well in Planet Wizard.
=> Reset all the options on model reload + hide some UI elements in Planet Wizard

js/plates-model/plate-draw-tool.ts
Reverts concord-consortium/tectonic-explorer#177
Finally, Amy didn't like the continental shelf being automatically added around boundaries, so I'm revering the PR that added that. See:
https://www.pivotaltracker.com/story/show/181127412
https://www.pivotaltracker.com/story/show/181127412/comments/229679395
=> Revert "Add continental shelf around plate boundary"

js/config.ts, js/plates-model/plate.ts, js/plates-view/force-arrow.ts, js/stores/helpers/boundary-utils.ts
[#181153609]
This PR makes user-defined forces (ones specified in Planet Wizard) much stronger and configurable. Previous values were too low and the orogeny wasn't really happening.
=> Make user-defined forces stronger to enhance continental collision

cypress/integration/basic/simulation-rules/continent-ocean-collision.js, cypress/integration/basic/simulation-rules/continental-collision.js, cypress/integration/basic/simulation-rules/divergentBoundary.js, js/config.ts, js/plates-model/model.ts, js/plates-model/plate.ts
https://www.pivotaltracker.com/story/show/181153609
Small updates related to plate forces. I've increased max plate velocity so the new param works with higher values too. Also, I generally increased forces but also made force decrease faster. This should accelerate plates faster, so the results are less dependent on the distance between continents.
This last update broke some model Cypress tests. They're very specific and bound to the current model behavior. They'll be way more changes to model behavior, so I think it makes sense to skip these problematic tests for now and update them at the end of dev cycle.
=> Update plate forces, skip some of the Cypress tests

js/config.ts, js/plates-interactions/base-interactions-manager.ts, js/plates-interactions/force-drawing.ts, js/plates-model/crust.ts, js/plates-model/field.ts, js/plates-view/force-arrow.ts, js/plates-view/plate-mesh.ts, js/presets.ts, test/plates-model/crust.test.ts
https://www.pivotaltracker.com/story/show/181254099
The main goal of this PR is to update continental crust and mantle thickness. 
Old:
New:
The mantle is easy, as it's just a visual layer. However, there's no single way to update continental thickness without affecting the model output. I've done two things:
1. I've changed the ratio of "mountain roots" (CRUST_THICKNESS_TO_ELEVATION_RATIO). This makes continental crust thinner, as its base elevation is unchanged (0.55). There's less of the crust below zero level.
2. I've shifted base ocean crust elevation a bit higher. That makes oceans shallower and decreases the total height of the continental crust.
However, both these updates make mountains taller, as more of the crust will "float" and also the base elevation is higher. That's why …
=> Update continent thickness, orogeny intensity + misc fixes

js/components/advanced-options.tsx, js/config.ts, js/plates-model/field.ts, js/plates-model/model-worker.ts, js/stores/simulation-store.ts
https://www.pivotaltracker.com/story/show/181392960
Time slider used to change timestep. I've been trying to include timestep in all the simulation rules, but it's still difficult to ensure that model produces a very similar result for various time step values. It is not well-defined and well-known math that could be tested and verified.
So, I've decided to change the time slider so it affects the number of calculations per second. This is a safer approach, even though it might be limited by the performance of the machine. But project team was more concerned about the model being too fast, not too slow, and slowing down should always work.
=> 181392960 time slider

css/bottom-panel.less, webpack.config.js
[#181096771]
The full-screen button is invisible in master:
https://tectonic-explorer.concord.org/branch/master/index.html?preset=subduction
=> Fix full screen button

css-modules/keys/rock-types.less, images/rock-key/svg/metamorphic-rock-high-grade-contact-metamorphism-diagram.svg, images/rock-key/svg/metamorphic-rock-high-grade-subduction-zone-diagram.svg, images/rock-key/svg/metamorphic-rock-low-grade-subduction-zone-diagram.svg, images/rock-key/svg/metamorphic-rock-medium-grade-subduction-zone-diagram.svg, js/colors/cross-section-colors.ts, js/components/keys/rock-types.tsx, js/plates-view/render-cross-section.ts, js/types.ts
https://www.pivotaltracker.com/story/show/180970003
This PR makes a few significant changes to Rock Key. The project team wanted to show different diagrams for Low/Medium/High Grade Metamorphic Rocks depending on whether the user clicked the rock in subduction zone or continent-continent collision.
However, they still wanted to show only one header for each grade. So, TecRock will expand this header with a different diagram, depending on the picked rock. If the user clicks the header directly, it'll open the Continental Collision variant by default. I find this interaction pretty weird, but it was the requirement, and I didn't have a better idea how to handle that (apart from showing 7 different headers in the key, but it wouldn't look great).
That's why Rock Key has now a strange entry …
=> Update Rock Key to differentiate different kinds of metamorphic rocks in each grade

js/components/planet-wizard.tsx, js/log.ts, js/plates-model/model.ts, js/stores/helpers/planet-wizard-model-validators.ts
https://www.pivotaltracker.com/story/show/181257654
A quite common problem in TecRock is that users draw a single continent at the boundary, set boundary type to be convergent, but they set the continental plate density to be higher than the neighboring oceanic plate. This results in an unallowed collision type that adds plenty of friction forces to stop continental subduction. So, the models comes to halt very quickly. Amy was concerned that users are getting confused by that.
This PR adds a new mechanism in Planet Wizard - each step might be validated and the user might be asked to make some changes. It's been used in the density selection step. So, if the validation function detects the use case described above, it'll suggest changing the density setup.
Demo: …
=> Add Planet Wizard validation pattern and check user-set densities

css/control-group.less, js/components/bottom-panel.tsx, js/components/control-group.tsx
PT: [[#181680353]/comment](https://www.pivotaltracker.com/story/show/181680353/comments/230928425)
>Can I ask for one minor detail to be implemented for the bottom control bar: the bubbly top of the buttons should span each button separately -- the Temp/Pressure tool and Take Sample tool -- rather than spanning both. But they should still always sit next to (abut) one another.
Done
=> Bottom bar tweak

package-lock.json, package.json
https://www.pivotaltracker.com/story/show/182036906
The last screenful version mentions in their readme:
> This package is ESM. Please [familiarize](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) yourself with that that implies.
If you cannot use ESM or need to support older browsers without using transpilation, use version 5.2.0.
Chris Lore sent me a screenshot from old Chromebook and it confirms the problem is in the screenfull package source.
I should probably learn more about ESM and its implications and consider some other options. But this looks like a quick and safe fix for now.
=> Downgrade screenfull to the last non-ESM version to avoid problems in older browsers.

js/plates-interactions/base-interactions-manager.ts, js/plates-interactions/cross-section-click.ts, js/plates-interactions/cross-section-interactions-manager.ts, js/plates-interactions/globe-interactions-manager.ts, js/plates-interactions/helpers.ts, js/plates-interactions/planet-click.ts
PT: [[#180335792]/comment](https://www.pivotaltracker.com/story/show/180335792/comments/231035077)
Demo: https://tectonic-explorer.concord.org/branch/polar-boundary/index.html
This was actually broken in #207 with the implementation of the temperature/pressure tool, but not noticed until working on the polar cap boundary highlighting story.
=> Boundary stays highlighted in presence of boundary selection dialog

js/config.ts, js/plates-model/field.ts, js/plates-model/get-cross-section.ts, js/plates-model/model.ts, js/plates-view/render-cross-section.ts
[#177579801]
Demo: https://tectonic-explorer.concord.org/branch/block-faulting/index.html?modelId=07823204-632d-4b05-8712-7f055b372e3a&rocks=true
This is as close as I could get to some drafts you posted in the PT story. The diagonal lines are fake, they just go within one column / field, but I think the visual effect works okay. The code turned out to be pretty small / simpler than expected (it also shows a complete round trip of data, from model to cross-section rendering code).
You can also change how strong is the faulting using a new url param:
- stronger: [https://tectonic-explorer.concord.org/branch/block-faulting/index.html?modelId=07823204-632[…]8712-7f055b372e3a&rocks=true&blockFaultingStrength=0.3](https://tectonic-explorer.concord.org/branch/block-faulting/index.html?modelId=07 …
=> Implement block faulting around cont-cont divergent boundaries

js/config.ts, js/plates-model/field.ts, js/plates-view/render-cross-section.ts
https://www.pivotaltracker.com/story/show/181799189
Demo: https://tectonic-explorer.concord.org/branch/thrust-faulting/index.html?modelId=550f18df-ad6e-4714-bc24-f021c64c5f2d&rocks=true
This PR adds thrust faulting around convergent continent-continent boundaries. PT story has a bit unclear description (I guess copied over from divergent boundary version) and the draft image there is very optimistic. But this is what I could do for now. Let's see what's the project team feedback.
=> Add thrust faulting around convergent boundaries

js/config.ts, js/plates-model/field.ts, js/plates-view/render-cross-section.ts
[#177579801]
[#181799189]
The project team requested a few changes:
- Shallower block faulting lines. They mentioned 40km, but not sure what that means. I've made that configurable.
- Weaker faulting. I've updated the default config balue.
- No faulting in the subducting plate during orogeny / continental collision. It's removed now.
- Sequential propagation of the faulting in the top blat during orogeny / continental collision rather than immediate change. I've done it by simplifying the logic. I don't propagate `blockFaulting` value anymore. Instead, I've just set it using subducting progress of the plate underneath. This makes the faults appear in succession.
=> Tweak block faulting

js/plates-model/field.ts, js/plates-model/generate-plates.ts, js/plates-model/get-cross-section.ts, js/plates-view/plate-mesh.ts, js/plates-view/render-cross-section.ts
https://www.pivotaltracker.com/story/show/180997501
This is only the beginning of the work. I've extended range of `normalizedAge` value from [0, 1] to [0, 5]. That let me easily show a wider range of crust age and it's more or less matching Michael's mocks. 
See: https://www.pivotaltracker.com/story/show/180997501/comments/230961040
`normalizedAge` is used in multiple places in the model, so I think it's important that this getter still behaves the same in [0,1] range. Multiple places in the model check if it's < 1, which seems fine here and saves us and makes implementation simpler.
A new property could also work, but it might be more confusing to have two separate concepts of age, more data to send between threads and to serialize.
I guess we could update the name of the getter. …
=> Extend range of the crust age visualization

js/components/authoring.tsx
PT: [[#182089196]](https://www.pivotaltracker.com/story/show/182089196)
Demo: https://tectonic-explorer.concord.org/branch/author-url/index.html?authoring
=> Always include `geode` param in authored urls [#182089196]

js/colors/topographic-colors.ts, js/plates-model/field.ts, js/plates-view/plate-mesh.ts
[#180997501]
This PR adds a new crust age visualization. It handles preexisting crust too.
Demo: https://tectonic-explorer.concord.org/branch/new-crust-age-vis/index.html?rocks=true&preset=divergentBoundary
=> Update crust age visualization

js/plates-view/render-cross-section.ts
In #232, @pjanik wrote:
>The new magma image is wider than a field column, so its right edge might be cut by the rendering of the next field. If we render the image after rendering all the fields, it should fix it.
=> Render divergent boundary magma after all fields

css-modules/keys/elevation-descriptions.less, css-modules/keys/elevation-labels.less, css-modules/keys/map-type.less, cypress/integration/basic/keysandoptions.js, images/topographic-color-key.svg, js/components/keys/elevation-descriptions.tsx, js/components/keys/elevation-key.tsx, js/components/keys/elevation-labels.tsx, js/components/keys/key-types.ts, js/components/keys/map-type.tsx, js/components/keys/plate-color-key.tsx
PT: [[#180992693]](https://www.pivotaltracker.com/story/show/180992693)
Demo: https://tectonic-explorer.concord.org/branch/elevation-key/index.html?rocks&preset=benchmark
Changes look more extensive than they really are due to moving `ElevationLabels` and `ElevationDescriptions` components out of the `PlateColorKey` component and into their own components since they're now shared with the new `ElevationKey` component. Since the two keys are different heights the layout code computes the vertical position of the labels in JavaScript rather than in CSS.
=> Implement new elevation (topographic) key design [#180992693]

js/plates-view/plate-label.ts, js/plates-view/point-label.ts
1. Plate label font size is adjusted based on the length of the label.
2. Plate labels are moved further above the surface.
=> Plate label updates

css-modules/side-container.less
Before:
Now:
It got broken a while ago, not sure when, so fixing it before I definitely leave the project. :)
=> Fix tabs styles

css-modules/keys/elevation-descriptions.less, js/components/keys/elevation-descriptions.tsx
[[#180992870]/comment](https://www.pivotaltracker.com/story/show/180992870/comments/231492751)
Fixes capitalization of elevation descriptions and adjusts the horizontal placement of the `Sea level` label.
=> Plate color key tweaks

js/plates-model/field.ts
[#182716231]
When I was working on the new crust age visualization (see: https://github.com/concord-consortium/tectonic-explorer/commit/a32429e93c2e37cbfd738422b83695a51fd3a537), I overlooked changing === 1 to new MAX_NORMALIZED_AGE.
This caused issues well described in the PT story: https://www.pivotaltracker.com/story/show/182716231
=> Fix initial location of oceanic sediment

js/plates-interactions/cross-section-interactions-manager.ts, js/plates-model/get-temp-and-pressure.ts
[[#182716184]](https://www.pivotaltracker.com/story/show/182716184)
Magma slug in convergent boundary isn't related to one field - it uses averaged position of multiple fields. That's why interaction doesn't return a single field object. But it returns rock type label. So, this PR updates the Measure Pressure/Temp tool to handle a case when only the rock label is available.
=> Magma slug in convergent boundary should be measurable with temp/pressure tool

js/plates-view/plate-mesh.ts, js/plates-view/temporal-events.ts
https://www.pivotaltracker.com/story/show/183023034
Volcanic eruption icons seemed to lag behind their correct position.
That has been fixed in the first commit here. Basically, the new position was saved in the `this.position` array, but then it wasn't used to recalculate geometry until visibility was updated. I've added positionNeedsUpdate to keep track of the position validity and update geometry when necessary. Also, the second commit adds more types to the temporal-events.ts file.
=> Fix volcanic eruptions positions

js/colors/rock-colors.ts, js/plates-model/get-cross-section.ts
[[#182974865]](https://www.pivotaltracker.com/story/show/182974865)
The problem was caused by the divergent boundary field that didn't specify normalized age. So, late it was assumed to be 0 and this was causing `getRockCanvasPatternGivenNormalizedAge` function to return `#333` colo. This color should be only used for the oceanic divergent boundary as a base for the red overlay.
=> Fix black column at boundary during continental divergence

js/config.ts, js/plates-view/render-cross-section.ts
The issue is well described in the PT story: https://www.pivotaltracker.com/story/show/182716121
This PR adds two params that will make the slug slightly smaller and make subduction plate subduct steeper (only visually) to avoid overlap of the subducting plate and the magma slug.
=> Reduce subduction magma slug width

js/plates-view/render-cross-section.ts
[#183128390]
Before fix:
The area marked in red still has low and medium-grade metamorphism even though these rocks are deep under the surface and should be marked as high-grade metamorphic rocks. This PR is fixing it.
After fix:
=> Make sure that rocks deep under the surface have high grade metamorphism overlay

js/plates-view/temporal-event-fragment.glsl, js/plates-view/temporal-events.ts
[[#183487545]](https://www.pivotaltracker.com/n/projects/2441249/stories/183487545)
This PR fixes an issue most likely caused by the THREE.JS version upgrade. ALPHATEST uniform is no longer available. I've tried to use `alphaTest` that seemed to be the right name based on the source code, but it still didn't work. It's not really critical, so I just hardcoded 0.5 (we could also not discard these pixels and nothing bad would happen).
=> Fix earthquakes rendering

css-modules/caveat-notice.less
[[#183763407]](https://www.pivotaltracker.com/story/show/183763407)
I think the issue was caused by the caveat notice:
Even if it's invisible, it's container was in the DOM. So, the main fix was to add `pointer-events: none` not to block the buttons that it overlaps.
Also, I've slightly updated styles to make it less likely to overlap the cross-section. Before:
After:
=> Update styles of earthquakes caveat notice to avoid conflicts with cross section buttons

js/components/planet-view.tsx
[#183681490]
This PR ensures that when you are selecting boundary type (Planet Wizard, 2nd step), the model won't highlight any other boundary segment.
=> Fix boundary highlighting

js/components/data-collection-dialog.tsx, js/components/simulation.tsx, js/plates-interactions/cross-section-interactions-manager.ts, js/stores/simulation-store.ts, js/types.ts
[[#183946419]](https://www.pivotaltracker.com/story/show/183946419)
This PR adds LARA Interactive API support. Tectonic Explorer can now save and load interactive state that mostly includes dataset that is going to be rendered by a new table interactive.
=> Manage LARA interactive state with dataset

js/components/cross-section-3d.tsx, js/plates-view/cross-section-3d.ts, js/plates-view/render-cross-section.ts, js/stores/simulation-store.ts, test/plates-view/render-cross-section.test.ts
[[#184003233]](https://www.pivotaltracker.com/story/show/184003233)
The basic cross-section markers rendering. They are going to have different shapes and need to be interactive most likely, so this is just a temporal solution.
=> Render data samples in the cross-section view

js/plates-view/cross-section-3d.ts, js/plates-view/planet-view.ts, js/shutterbug-support.ts, js/stores/simulation-store.ts, js/types.ts
[#184027345]
Tectonic Explorer will now save two screenshots when it saves the interactive state. It isn't visible for users (until they look at the TecRock Table), and I'm trying to ensure that we never overwrite newer screenshots with older ones. This could happen easily, as the Shutterbug response time is very variable and usually the first request is the slowest.
=> Save globe view and cross-section snapshots in interactive state

js/stores/simulation-store.ts
[#184074513]
[#184074641]
This PR disables initial interactive state saving, as that's not really useful and it was causing some issues.
Also, the dialog informing about data saving won't be shown if there are samples to save.
Finally, the forward navigation is re-enabled with a small delay, so it's less likely user is able to change page when AP is saving the updated state in Firestore. Plus I've added one MobX `action` wrapper to avoid warnings.
=> Fix issues related to data saving

js/stores/simulation-store.ts
[#184074641]
A silly bug, `setNavigation` call was outside the `if` clause.
=> Fix navigation unlocking

packages/shared/types.ts, packages/tecrock-table/src/components/app.tsx, packages/tecrock-table/src/components/runtime.scss, packages/tecrock-table/src/components/runtime.tsx, packages/tecrock-table/src/types.ts, packages/tectonic-explorer/js/stores/simulation-store.ts
[[#184185704]](https://www.pivotaltracker.com/story/show/184185704)
Two main changes in this PR:
1. I've given up on using `IDataset` in Tectonic Explorer interactive state. It became pointless, as this dataset cannot be rendered by any generic interactive. Most of the data in the table are derived from rock type, and there are plenty of SVGs that need to be injected. Also, now TecRock Table and Tectonic Explorer live in the same repository and use `shared` package, so there's no problem in sharing the interactive state interface between them.
2. I've updated TecRock Table rendering to match table in the Tectonic Explorer Data Collection dialog.
=> TecRock Table updates

packages/shared/data-sample-info.tsx, packages/shared/types.ts, packages/tecrock-table/src/components/runtime.scss, packages/tecrock-table/src/components/runtime.tsx, packages/tectonic-explorer/js/components/data-collection-dialog.tsx, packages/tectonic-explorer/js/stores/simulation-store.ts
[#184214544]
This PR ensures that notes texarea (TE dialog) and notes column (TecRock Table) are disabled when "notes" value is not present in `dataSampleColumns` config value. I've also fixed some styles and ensured that column are always rendered in the same order.
=> Add notes support

packages/tectonic-explorer/js/components/data-collection-dialog.tsx, packages/tectonic-explorer/js/components/draggable-dialog.tsx, packages/tectonic-explorer/js/stores/simulation-store.ts
The bug was pretty weird, but it's well described by Saravanan here:
https://www.pivotaltracker.com/story/show/184074624/comments/235007860
Half of the problem was:
```
this.currentDataSample.notes = notes;
```
instead of:
```
this.currentDataSample = {
...this.currentDataSample,
notes
};
```
but that revealed another problem in the dialog. The notes textarea was losing focus on each key stroke. That's fixed by memoization of the PaperComponent.
=> Fix a bug in Data Collection dialog (notes textarea)

packages/tectonic-explorer/js/components/cross-section-3d.tsx, packages/tectonic-explorer/js/stores/simulation-store.ts
[[#184186030]](https://www.pivotaltracker.com/story/show/184186030)
This PR:
1. Locks CS view in the data collection mode (first commit)
2. Fix a small random bug - sometimes data collection dialog could be visible even after user extits the data collection mode (second commit)
=> Prevent cross section rotation in data collection mode

packages/tectonic-explorer/css-modules/data-saving-dialog.less, packages/tectonic-explorer/css-modules/exit-data-collection-dialog.less, packages/tectonic-explorer/js/components/bottom-panel.tsx, packages/tectonic-explorer/js/components/data-collection-dialog.tsx, packages/tectonic-explorer/js/components/data-saving-dialog.tsx, packages/tectonic-explorer/js/components/exit-data-collection-dialog.tsx, packages/tectonic-explorer/js/components/simulation.tsx, packages/tectonic-explorer/js/log.ts, packages/tectonic-explorer/js/stores/simulation-store.ts
[[#184186037]](https://www.pivotaltracker.com/story/show/184186037)
[[#184230774]](https://www.pivotaltracker.com/story/show/184230774)
This PR changes what happens after user clicks "Collect Data" button to exit data collection mode. The expected workflow is described in the PT story: https://www.pivotaltracker.com/story/show/184186037
I've also added a new story that covers logging, as it seems it might be useful for the MVP and first tests with users.
=> Redesign exit data collection dialog, add logs related to data collection

packages/tecrock-table/src/assets/zoom-in.svg, packages/tecrock-table/src/components/runtime.scss, packages/tecrock-table/src/components/runtime.tsx, packages/tectonic-explorer/css-modules/data-collection-dialog.less, packages/tectonic-explorer/css-modules/exit-data-collection-dialog.less
[[#184186001]](https://www.pivotaltracker.com/story/show/184186001)
This PR lets user expand snapshots in a lightbox:
There are two separate buttons, as the current Interactive API `showModal({ type: "lightbox" })` accepts only one image URL. 
I could use  `showModal({ type: "dialog" })` and render an iframe with two images together, but this approach has some issues. AP dialog implementation is slightly broken and doesn't show the close icon and doesn't let the user close the dialog using backdrop (I've added a PT bug: https://www.pivotaltracker.com/story/show/184232312). Also, the dialog size won't match the image and there's not much we could do about it. It'd be also more code here. So, I'm trying this approach for now, as it's cleaner and lightbox UX is nicer for users.
=> TecRock table: let users expand snapshots in a lightbox

packages/tectonic-explorer/css-modules/enter-data-collection-dialog.less, packages/tectonic-explorer/js/components/bottom-panel.tsx, packages/tectonic-explorer/js/components/enter-data-collection-dialog.tsx, packages/tectonic-explorer/js/components/simulation.tsx, packages/tectonic-explorer/js/log.ts, packages/tectonic-explorer/js/stores/simulation-store.ts
[[#184232569]](https://www.pivotaltracker.com/story/show/184232569)
This PR replaces the native browser confirm dialog with a custom one that is consistent with other dialogs that we use in data collection mode. It also adds a few log messages.
=> Replace native alert with custom dialog that asks for clearing previously saved data

packages/tectonic-explorer/js/stores/simulation-store.ts
[[#184238480]](https://www.pivotaltracker.com/story/show/184238480)
This PR fixes a bug that is nicely described in the PT story. I was disabling navigation and never enabling it again if snapshots were not saved (what happens after data is cleared).
=> Tectonic Explorer: fix navigation locking

packages/tectonic-explorer/js/get-threejs-renderer.ts, packages/tectonic-explorer/js/plates-view/cross-section-3d.ts
This PR fixes the issue described in the PT story: [[#184239320]](https://www.pivotaltracker.com/story/show/184239320)
It was pretty hard to debug, but apparently, when the same renderer was reused multiple times, OrbitControls were not working correctly anymore. I was disabling rotation correctly, but after the whole CrossSection3D was recreated with an old renderer, setting a flag related to camera rotation in OrbitControls had no longer any effect. 
I tried to create a new renderer each time when the component is created and it works fine. I don't think there's any drawback to this approach. Maybe I was trying to reuse one render for some performance reasons, but I don't think it matters.
=> Fix cross-section rotation lock in Data Collection mode

packages/tectonic-explorer/src/state-migrations.ts, packages/tectonic-explorer/src/stores/simulation-store.ts
[[#184421894]](https://www.pivotaltracker.com/story/show/184421894)
More context: https://concord-consortium.slack.com/archives/C01F450JVE1/p1675707376900469 
Trudi noticed that TE interactives that load serialized models don't work anymore. I accidentally made TE v2.5.0 not backward compatible with v2.4.1. This was not necessary. This PR updates the version number of the serialized state and adds automatic migration.
=> Update serialized state version, add v4 to v5 migration

packages/tecrock-table/src/components/runtime.tsx
Before, placeholder graphic was only displaying when the dataSamples array was not defined, which led to the graphic not displaying when collection data was cleared. Now, display the graphic when array is defined but has no length.
=> Display placeholder graphic when data is cleared. (PT-185002145)

package-lock.json, packages/tectonic-explorer/package.json, packages/tectonic-explorer/src/components/simulation.tsx, packages/tectonic-explorer/src/peels/sphere/int-arr.ts, packages/tectonic-explorer/src/peels/sphere/to-cg.ts, packages/tectonic-explorer/src/plates-interactions/helpers.ts, packages/tectonic-explorer/src/plates-view/cross-section-3d.ts, packages/tectonic-explorer/src/plates-view/earthquake-helpers.ts, packages/tectonic-explorer/src/plates-view/n-pole-label.ts, packages/tectonic-explorer/src/plates-view/planet-view.ts, packages/tectonic-explorer/src/plates-view/plate-mesh-fragment.glsl, packages/tectonic-explorer/src/plates-view/plate-mesh-vertex.glsl, packages/tectonic-explorer/src/plates-view/plate-mesh.ts, packages/tectonic-explorer/src/plates-view/point-label.ts, packages/tectonic-explorer/src/plates-view/temporal-event-fragment.glsl, packages/tectonic-explorer/src/plates-view/volcanic-eruption-helpers.ts
https://www.pivotaltracker.com/story/show/186622948
This PR updates ThreeJS to r160. Necessary changes include:
- Updating custom shaders. This is expected, and I hope my improved comments make future modifications easier.
- Updates necessary to address the new color management introduced in ThreeJS r152/153: [ThreeJS Color Management](https://threejs.org/docs/#manual/en/introduction/Color-management). This is a bit painful, as there is no way to convert the code and achieve exactly identical results. Thus, the updates involve setting the correct color space in various places, converting some colors from sRGB to linear sRGB, and adjusting lighting.
- One of the more recent ThreeJS versions also updated the logic related to bump mapping. This required some tweaking of the TecRock code to …
=> Update ThreeJS to r160

packages/tecrock-simulation/src/plates-view/render-cross-section.ts, packages/tecrock-simulation/test/plates-view/render-cross-section.test.ts
https://www.pivotaltracker.com/story/show/186761171
The PT story should describe the reasons and goals behind this change. The `.setTransform` method has made this change quite concise. Initially, I was concerned that I would need to render patterns manually using rectangles + clipping.
I think it works quite well in practice. Let's see what the project team says.
=> Update the rock pattern rendering so that the pattern follows the position of the cells rather than being stationary

packages/shared/data-sample-info.tsx, packages/tecrock-simulation/src/components/keys/rock-types.tsx
A small PR addressing the comments made by Chris Lore on this PT story: https://www.pivotaltracker.com/story/show/185032941/comments/239929908. 
It corrects one incorrect diagram path and makes a few updates to the description wording.
=> Update descriptions of rock, fix wrong diagram path

packages/tecrock-simulation/src/components/keys/rock-types.scss, packages/tecrock-table/src/components/report-item/report-item.tsx, packages/tecrock-table/src/components/table.scss, packages/tecrock-table/src/components/table.tsx
https://www.pivotaltracker.com/story/show/186921649
https://www.pivotaltracker.com/story/show/186921720
This PR scales down the table in the Question Details view and allows teachers to enlarge snapshots. It's done using a pretty basic JavaScript script, as the report-item doesn't have access to any libraries. Fortunately, in this case, the basic DOM API was sufficient.
=> Scale down the table in the Question Details view, allow teachers to enlarge snapshots

packages/tecrock-table/src/components/report-item/report-item.tsx
This PR addresses the issue that Saravanan described in the second bullet point of his comment, which can be found here: https://www.pivotaltracker.com/story/show/186921649/comments/240062521
The issue is actually triggered by the dashboard animation of the report item container.
=> Fix report-item layout script

packages/tecrock-simulation/src/index.html, packages/tecrock-simulation/webpack.config.js
https://www.pivotaltracker.com/story/show/186957289
This doesn't seem related to the bug, but I believe the issue is that the script tag was added twice: once via HtmlWebpackPlugin and then again through an explicit `<script src="app.js"></script>` line. This wasn't visible in most cases because the same script was loaded twice, until we released this project to production. Two slightly different scripts were loaded (from `version/v2.7.0` and top-level production dir), which possibly caused the linked bug.
=> Fix index.html template

packages/tecrock-simulation/src/global.d.ts, packages/tecrock-simulation/src/worker-controller.ts, packages/tecrock-simulation/webpack.config.js
This PR addresses @scytacki's comment:
https://github.com/concord-consortium/tectonic-explorer/pull/354#discussion_r1487063479
It simplifies the configuration slightly.
I tested it both using webpack-dev server and on production (releasing v2.7.2-pre.1) and it seems to work fine.
=> Use built-in __webpack_public_path__ instead of custom global variable

packages/tecrock-simulation/src/storage.ts
Obfuscated Firebase API key using atob() so that automated key leak detectors are not falsely triggered.
NOTE: the Firebase API key is a public key so this does not leak secrets.
=> chore: Obfuscated Firebase API key [PT-187643494]

packages/tecrock-simulation/cypress/e2e/basic/state-migration-error.js, packages/tecrock-simulation/src/state-migrations.ts
This will allow older models to load from S3 instead of Firebase
=> build: Update latest v1 url to v1.4.4
